spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_food_order_system?createDatabaseIfNotExist = true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show_sql : true